name: Deploy Storage Rules
on:
  push:
    paths:
      - 'storage.rules'
      - '.github/workflows/storage.workflow.yml'

jobs:
  deploy:
    if: contains(github.ref, 'dev')
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only storage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: 'jaspero-jms'
